### ISSUE TITLE
file paramter issues while running docker compose up

### ISSUE THREAD

**Issue by mozzam4** [uhh-lt/targer#53]
Dear Team, 
I get following error while running docker-compose up. I have downloaded the files and also placed them at right location.539106

backend_1   | Using TensorFlow backend.
backend_1   | /usr/local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:493: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
backend_1   |   _np_qint8 = np.dtype([("qint8", np.int8, 1)])
backend_1   | /usr/local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:494: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
backend_1   |   _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
backend_1   | /usr/local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:495: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
backend_1   |   _np_qint16 = np.dtype([("qint16", np.int16, 1)])
backend_1   | /usr/local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:496: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
backend_1   |   _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
backend_1   | /usr/local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:497: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
backend_1   |   _np_qint32 = np.dtype([("qint32", np.int32, 1)])
backend_1   | /usr/local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:502: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
backend_1   |   np_resource = np.dtype([("resource", np.ubyte, 1)])
backend_1   | Traceback (most recent call last):
backend_1   |   File "backend.py", line 17, in <module>
backend_1   |     from ModelNewES import ModelNewES
backend_1   |   File "/emnlp2017-bilstm-cnn-crf/ModelNewES.py", line 14, in <module>
backend_1   |     class ModelNewES:
backend_1   |   File "/emnlp2017-bilstm-cnn-crf/ModelNewES.py", line 16, in ModelNewES
backend_1   |     tagger =TaggerFactory.load(path, -1)
backend_1   |   File "/emnlp2017-bilstm-cnn-crf/lstm/src/factories/factory_tagger.py", line 16, in load
backend_1   |     "--save-best-path" param to create it.' % checkpoint_fn)
backend_1   | ValueError: Cant find tagger in file "models/model_new_es.hdf5". Please, run the main script with non-empty                              "--save-best-path" param to create it.
targer_backend_1 exited with code 1

**Comment by janheinrichmerker** [comment]
Hi @mozzam4, you could try the [webis-de/targer](https://github.com/webis-de/targer) branch. The Hamburg branch hasn't seen updates in a while and we fixed some bugs in our branch. Also you can use our pre-built Docker images: [`webis/targer-frontend:1.0`](https://hub.docker.com/r/webis/targer-frontend) and [`webis/targer-backend:1.0`](https://hub.docker.com/r/webis/targer-backend).
